## Menu html

Here is the menu generated by WordPress:

~~~~
<!-- the menu looks like this -->
<div class="menu">
		<div class="menu-dawn-container">
			<ul id="menu-dawn" class="menu">
				<li id="menu-item-174" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-174">
					<a href="http://localhost/wordpress/index.php/zzzzzzzzzzzzzzzzz/">SQL Sample</a></li>
				<li id="menu-item-195" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-195"><a href="http://localhost/wordpress/index.php/2015/08/05/forta/">Forta</a></li>
				<li id="menu-item-180" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-has-children menu-item-180"><a href="http://localhost/wordpress/index.php/full-width/">Full Width</a>
					<ul class="sub-menu">
						<li id="menu-item-177" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-177"><a href="http://localhost/wordpress/index.php/sample-page/">Sample Page</a></li>
						<li id="menu-item-178" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-178"><a href="http://localhost/wordpress/index.php/lightbox/">Lightbox</a></li>
						<li id="menu-item-175" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-175"><a href="http://localhost/wordpress/index.php/the-tutorial-site/">The Tutorial Site</a></li>
	<li id="menu-item-190" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-190"><a href="http://localhost/wordpress/index.php/hey/">Hey</a></li>
					</ul>
				</li>
				<li id="menu-item-181" class="menu-item menu-item-type-post_type menu-item-object-page menu-item-181"><a href="http://localhost/wordpress/index.php/about-2/">About</a></li>
				<li id="menu-item-203" class="menu-item menu-item-type-custom menu-item-object-custom menu-item-203"><a href="http://localhost/wordpress/index.php/2015/08/07/online-databases/">Databases and the WWW</a></li>
			</ul>
	</div>+
</div>
~~~~

## Classes

So we get the structure for the .css files:

~~~~
	- .menu
		- .menu-item (.menu-item-has-children)
			- .sub-menu 
				- .menu-item
~~~~

## SASS

Which leads to some sassy stuff:

## Links

[Style sub-menu](https://www.youtube.com/watch?v=-FssrDuy8-U)

